### ISSUE TITLE
 full screen 3024 x 1964 cmd + tab Switch out Window size is abnormal

### ISSUE THREAD

**Issue by Caikishi** [marzent/XIV-on-Mac#104]
full screen 3024 x 1964 cmd + tab Switch out Window size is abnormal

**Comment by FleetAdmiralButter** [comment]
Exclusive fullscreen can be a bit buggy, especially with custom resolutions.

Recommend you use Borderless Windowed to play and adjust your desktop scaling to match.

**Comment by Caikishi** [comment]
> Exclusive fullscreen can be a bit buggy, especially with custom resolutions.
> 
> Recommend you use Borderless Windowed to play and adjust your desktop scaling to match.

Hello, I'm glad you can answer my question 
Now because game has dynamic resolution
The game can run smoothly in 3024 x 1964
Borderless full-screen is no problem, but the picture is not clear

**Comment by marzent** [comment]
The resolution being a quarter of what the physical display has is due to macOS scaling, which you can disable in settings
