### ISSUE TITLE
Symbols in chat instead of russian language

### ISSUE THREAD

**Issue by AAfetisov** [marzent/XIV-on-Mac#130]
Whatever I type in russian looks like symbols. Other people also see me typing symbols, but I can see their russian just fine
<img width="517" alt="Screenshot 2023-08-18 at 01 24 58" src="https://github.com/marzent/XIV-on-Mac/assets/1430709/ca7627d3-1aec-447b-863d-08daa00bc526">

I searched for a solution but didn't find any. Probably something to do with how wine is set up?

my Os is Sonoma beta, game license - steam

**Comment by AAfetisov** [comment]
I tried changing setup() function in **Wine.swift** file but it didn't help
https://github.com/marzent/XIV-on-Mac/blob/main/XIV%20on%20Mac/Wine.swift
 with things like these in different combinations
```
addEnvironmentVariable("LANG", "ru_RU")
addEnvironmentVariable("LC_MESSAGES", "ru_RU")
```
```
addEnvironmentVariable("LANG", "ru_RU.UTF-8")
addEnvironmentVariable("LC_MESSAGES", "ru_RU.UTF-8")
```
```
addEnvironmentVariable("LC_ALL", "ru_RU.UTF-8")
addEnvironmentVariable("LC_ALL", "ru_RU")
```

**Comment by AAfetisov** [comment]
its most probably macos or xiv issue

**Comment by marzent** [comment]
Well that issue is indeed somewhat known and a bad interaction between wine and the game (it seems Cyrillic characters are correctly input with wine 4.X)
This is a bit tricky to debug and for sure a wine regression.
