### ISSUE TITLE
Can't start downloading

### ISSUE THREAD

**Issue by onlineid** [marzent/XIV-on-Mac#132]
Fresh install. downloading process is not moving, the client is frozen, has to "Force quite". 
Screenshot attached.

<img width="966" alt="Screenshot 2023-08-28 at 18 38 47" src="https://github.com/marzent/XIV-on-Mac/assets/95579647/9cbababb-0d37-4684-83d9-024a05264366">

Macbook Pro (M1)
Mac OS 13.4
Anti-virus: Avira (Turn-off)

Thanks.

**Comment by willluongo** [comment]
I have the same issue on a Macbook Pro (Apple M1 Max) running 12.6.8 (21G725). I haven't been able to find anything in the console though there is an entry in Diagnostic Reports for XIV on Mac.

**Comment by seathasky** [comment]
You are welcome to post your logs here or use our support channel in discord and I can assist you there!

**Comment by seathasky** [comment]
Going to assume this has been fixed since there was no reply.

**Comment by bhajneet** [comment]
If you start off with a fresh install, I did have to force quit app and restart for the download to begin. So I would say it's still an issue, but not a blocking one / without workarounds.
