### ISSUE TITLE
New version 4.10.4 just hangs on a black screen

### ISSUE THREAD

**Issue by Ericchi** [marzent/XIV-on-Mac#135]
Hello, it's me again. I updated to 4.10.4 and now the game doesn't launch anymore. It hangs on a black screen with the rainbow spinner cursor.
I'm on Mac OS Sonoma, on a Macbook Air M2.
<img width="1392" alt="Screenshot 2023-09-28 at 11 27 34 PM" src="https://github.com/marzent/XIV-on-Mac/assets/3612472/efe2cab2-f754-4170-8c6d-e7ae95072f6a">

**Comment by seathasky** [comment]
Check announcements in our discord for a fix: https://discord.com/invite/dWN5bTC4Yv
