### ISSUE TITLE
Version 4.10.4 starts to freeze after playing for some time

### ISSUE THREAD

**Issue by wwingYu** [marzent/XIV-on-Mac#136]
After upgrading to 4.10.4 yesterday, the game started to lag / even freeze after playing for some time / resizing the window / switching between desktops. I had forced quit the software and restart but in vain, downgraded to 4.10.2 eventually.

I'm using Mac mini with Apple M2 Pro Chip for now, not sure if I have to stick to this version or not.

**Comment by ziegfeld** [comment]
XIV on Mac toolbar - "Tools" - "Troubleshooting.." -> Shader Cache section - "Delete User Shader Cache" button could help.
Saw it on the official discord discussions.
Thanks.
