### ISSUE TITLE
Version 4.12.1 (139) - "Error string FFXIV" but everything works?

### ISSUE THREAD

**Issue by Shirk** [marzent/XIV-on-Mac#137]
Since updating to 4.12.1 (139) today I get the following error whenever I start XIV:

> Error starting FFXIV
> An error during game startup has occurred.

The game launches and runs fine and without issue but XIV-on-mac always gives that message now.

**Comment by seathasky** [comment]
It's a known issue and can be ignored. We're looking into it! Thanks

**Comment by dropbeardevs** [comment]
This is linked to #127, please refer to it for a workaround!
