### ISSUE TITLE
Official launcher error with existing crossover install

### ISSUE THREAD

**Issue by BahaVv** [marzent/XIV-on-Mac#14]
XIV on Mac Alpha v2.0.1
M1 Pro chip, 16GB RAM, macOS Monterey 12.1

This one's pretty simple, but I figured I'd mention it since I bumped into it, and others are also likely to do so.

I was previously using the version of this project that installed via Crossover, which appears to have resulted in a configuration that causes the game to attempt to use the newest version of the launcher, despite having deleted the bottle.  This causes the game to fail to launch as a result, hanging on a blank launcher page.

<img width="1279" alt="Screen Shot 2022-01-03 at 2 21 45 PM" src="https://user-images.githubusercontent.com/4324417/147972788-6717c371-7bdd-4149-bcb5-0dbbcebb4c59.png">

This can be rectified by deleting the `~/Documents/My Games/FINAL FANTASY XIV - A Realm Reborn` folder and reinstalling XIV on Mac -- it seems possible that just deleting the `FFXIV_BOOT.cfg` file without a reinstall would fix this, though I didn't test it.

It may be to the project's benefit to delete the file if it exists, as it seems likely people will eventually migrate over to this project from the old one.

This also brings up the issue that there's seemingly no documented uninstall guide -- I believe it's as simple as deleting the application and the `~/Library/Application Support/XIV on Mac` folder, but mentioning that somewhere obvious would be nice!

**Comment by xis666** [comment]
open Documents/My Games/FINAL FANTASY XIV - A Realm Reborn/FFXIV_BOOT.cfg
**Browser “1”**

You can use the old launche

![DE4FDC1B-AC04-4450-8D42-D35EEB98ED7B](https://user-images.githubusercontent.com/58455001/148548070-d16cf795-6fa0-455d-8e90-e75b5b813288.jpeg)
r

**Comment by seathasky** [comment]
> This also brings up the issue that there's seemingly no documented uninstall guide -- I believe it's as simple as deleting the application and the `~/Library/Application Support/XIV on Mac` folder, but mentioning that somewhere obvious would be nice!

The project is in alpha. Any questions you may have can be asked in our discord. 

Our app is only 2-3 weeks old at this point and is constantly changing every release. 
Please do not expect too much from a tiny crew of people who have day jobs. We add stuff to the website when we can, usually very slowly. 

99% of issues are reported in our feedback/support channels on the Discord, including 
"how to uninstall". 

If you need help, use the Discord support channel, and i'd advice keeping expectations in check. 

Come join us in our discord here: https://xivmac.com/discord   we'd love to help you!

**Comment by marzent** [comment]
I’ve marked this issue as won’t fix since you need to have an extremely special setup in order to encounter this and I’d rather not touch game configuration files that already exist (the user might’ve set things up intentionally to test stuff out)

Crossover leaving residual files is not a defect of the app as well…
