### ISSUE TITLE
System Info

### ISSUE THREAD

**Issue by IgshFirn** [marzent/XIV-on-Mac#147]
Hello,
how can I deactivate the add-on in the upper right corner that shows my computer configuration? Thanks for the help!
![Screenshot 19 05 2024 um 11 35 35 AM](https://github.com/marzent/XIV-on-Mac/assets/29152086/34ad9e2c-218e-4274-8102-2c76e81ec6e8)
![Screenshot 19 05 2024 um 11 13 41 AM](https://github.com/marzent/XIV-on-Mac/assets/29152086/13159539-6e5c-456f-8a91-5ecfee1aaa4f)

**Comment by seathasky** [comment]
Unrick "Metal 3 Performance HUD"

**Comment by IgshFirn** [comment]
Thank you very much!
