### ISSUE TITLE
Uninstall Reshade

### ISSUE THREAD

**Issue by HendrikPetertje** [marzent/XIV-on-Mac#149]
Hey all!

I've installed Reshade on XIV for mac by running the installation steps earlier:
https://www.xivmac.com/reshade

I am noticing a lot of instability to my game with reshade running in the background (even when i don't use any plugins). I'd like to get rid of Reshade especially now that the new XIV patch will already do some of the quality of life improvements that I used to achieve with Reshade. 

There is no uninstall option sadly. Online I read that I should be able to just rename dxd9 or dxd11 DLL in the game folder, but my game folder doesn't seem to have either of these files (while it does have ReShade.log, ReShade.ini, d3dcompiler_47.dll and ReShadePreset.ini.

How do i proceed with uninstalling Reshade?

**Comment by seathasky** [comment]
DXGI.dll is the library the injects Reshade. All that is needed is to remove that file. If you want a full cleanup, delete the shaders/textures folders if you installed that, d3dcomplier_47.dll and all the relevant reshade .ini files.
