### ISSUE TITLE
XIV on MAC crashes upon opening

### ISSUE THREAD

**Issue by nocklobsey** [marzent/XIV-on-Mac#152]
The launcher crashes upon opening. WineDbg is unable to attach the process to obtain a backtrace as well. 
![Screenshot 2024-07-25 at 10 35 53 AM](https://github.com/user-attachments/assets/0f58394e-b567-4757-b9c6-5457c56eb838)

**Comment by nocklobsey** [comment]
I am using version 4.15 (160)

**Comment by seathasky** [comment]
We're currently looking into the issue with our latest release, please revert to 4.14.1: https://softwareupdate.xivmac.com/sites/default/files/update_data/XIV%20on%20Mac4.14.1.tar.xz

If you are still having issues getting game after reverting, cmd+i on launcher, delete "wineprefix" and restart your Mac.

**Comment by nocklobsey** [comment]
You guys are the best, thank you so much.

**Comment by seathasky** [comment]
> You guys are the best, thank you so much.

We still need more testing on 4.15 so if you follow these steps, you should be able to get it working: 

CMD+i on the launcher, delete the "Wineprefix" folder and **restart your Mac**. 

If you have any game license issues after deleting the wineprefix folder when you return from restarting, go to XOM settings in top menu, change your license to something other than your current license and then back and this should fix this issue.

**Comment by seathasky** [comment]
For further fixes on this issue, please check out the announcement section on our discord: https://www.xivmac.com/discord
