### ISSUE TITLE
FFXIV Crashes when I try to start the game "An error during game startup has occured".

### ISSUE THREAD

**Issue by crleekwc** [marzent/XIV-on-Mac#154]
I get the error "An error during game startup has occured" when trying to start up FFXIV after upgrading XIVonMac from 4.14.1 to 4.15.1, I currently have currently running and M1 Max 16" Macbook 2021 on Sonoma 14.6 .

**Comment by seathasky** [comment]
Somewhat a repeat issue ticket here. We're about to release 4.16 that fixes all of this. Either check discord or give the app a few and check updates

**Comment by crleekwc** [comment]
Ah okay, yeah I just saw the update available and it is working now. Thanks for the update :)
