### ISSUE TITLE
PS5 Touchpad Support

### ISSUE THREAD

**Issue by jagreenwood** [marzent/XIV-on-Mac#160]
The PS5 Dualsense touchpad does not seem to be supported. Tapping it doesn't do anything. 
Currently tapping the share button cycles through HUD elements. Ideally tapping the touchpad button would cycle the HUD as that is the behavior on PS5.

**Comment by seathasky** [comment]
This is not supported by FFXIV. Even on Windows, you need a program such as DS4Windows. AFAIK, there is no alternative or similar program on Mac. This is not a XOM issue.
