### ISSUE TITLE
wined3d.dll Error on Login/FFXIV App Launch

### ISSUE THREAD

**Issue by Kedochv2** [marzent/XIV-on-Mac#20]
Howdy FOM Team,

I get the following error when attempting to login using both v2.2.1 and v2.3.0 of FOM.
<img width="514" alt="Screen Shot 2022-01-22 at 1 11 56 PM" src="https://user-images.githubusercontent.com/98234005/150652583-e8988c6f-db18-40df-8c6f-093aca4ab587.png">

The above always happens after entering credentials and attempting to login. You'll notice the launcher attempts to open the game but then the wined3d.dll error occurs.

This is very similar to an error the official launcher gives me if I login but fail to launch the game in a timely manner (I'll attempt to recreate and post this dialogue if requested). 

Running:
13" Macbook Pro M1 (2020)
16 GB RAM
MacOS Monterey 12.1
Full Mac license of the game, operates normally using the official launcher.
When I first attempted this w/ v2.2.1 I used the Sym-link option to install FOM.

Available on Discord in the server, same screen name w/ Tester role - feel free to contact me there as well.

**Comment by HoshiYamazaki** [comment]
Same here: https://github.com/marzent/XIV-on-Mac/issues/22

**Comment by HoshiYamazaki** [comment]
This issue can be resolved by installing DXVK, via launcher, or by manually moving files and editing it via `winecfg`.

**Comment by marzent** [comment]
Resolved with https://github.com/marzent/XIV-on-Mac/pull/30
