### ISSUE TITLE
Add AMD CPUs support by omitting 32-bit dependencies

### ISSUE THREAD

**Issue by HoshiYamazaki** [marzent/XIV-on-Mac#22]
Hello,
So, basically CrossOver 20/21 has problems with running 32-bit code on AMD cpus:
https://github.com/AMD-OSX/bugtracker/issues/6
Not really discussing issue here, because nobody knows really why it happens (some people tells that it's 32 bit code exec fault, some tells you that it's caused by PAT patch stuff etc.), the issue also happens on `XIV-on-Mac` mod.

What we can do about it?
There are two things to consider - waiting for CrossOver 22, and checking if it resolves AMD CPU support (since it uses odd ldt calls logic as solution to 32-bit code removal since Catalina), or, resolving the mod to not use 32-bit code at all. And I think the second option is far far better, because we really don't know if CrossOver 22 will resolve the issue, but I heard from CodeWeavers member that they want to change the solution (maybe to VT-d based)?

Also, if there is anybody with AMD Hackintosh - testers are wanted. I know there are various CPUs, that can be affected and not really sure if it happens outside Ryzen series and if there is no necessity to write another solution. Also I'm quite interested in the performance on various builds, but this is other problem.

_Worth mentioning that threadrippers don't have 32-bit code bug!_

**Comment by seathasky** [comment]
Just like @marzent said in discord, use this pre-release: https://github.com/marzent/XIV-on-Mac/releases/tag/v2.99

Stick a full game inside the XIV on Mac prefix.

**Comment by HoshiYamazaki** [comment]
Tried it and this errors appears:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/21007545/154308685-f89d1eb8-59bb-45e9-b403-395daa30dcfe.png">

**Comment by HoshiYamazaki** [comment]
> Tried it and this errors appears: <img alt="image" width="348" src="https://user-images.githubusercontent.com/21007545/154308685-f89d1eb8-59bb-45e9-b403-395daa30dcfe.png">

So, by now, you can fix the issue by just installing DXVK. On AMD Hacks the internal installer is probably broken, so you manually must copy dxvk dir content into the game `system32` wine bottle dir, and run wine configuration (`winecfg`) to switch DirectX11 and DXGI libraries to `built-in`.

Still, I prefer OOB solution, so the issue STILL can't be closed.

**Comment by marzent** [comment]
64 bit only systems work OOB as of 3.0, the dxvk install failing is a different issue that should probably be tracked separately and not inherent to 64 bit support
