### ISSUE TITLE
Money coffee contribution

### ISSUE THREAD

**Issue by MykolaGolubyev** [marzent/XIV-on-Mac#25]
Hello,
I am super happy that I don't need to pay for crossover to enjoy the game with better FPS (or lower GPU consumption).
And I want to say thank you buy donating money. I couldn't find any links on the website to do so.

**Comment by seathasky** [comment]
Ty for the thought. Unfortunately we are only accepting Discord nitro boost to our Discord server which helps our entire community. Our project is free and open source to everyone.

**Comment by marzent** [comment]
Yeah it is much appreciated but I am not a huge fan of coffee ;)
If you do really want to spend some money a discord boost is always appreciated
