### ISSUE TITLE
Textures are all black

### ISSUE THREAD

**Issue by 0xChief** [marzent/XIV-on-Mac#27]
All of the environment textures are completely black; I can only see my HUD and the characters + NPCs. 

What the fix? Macbook pro on apple silicon.

**Comment by blackshuu** [comment]
I'm having the same issue, is there a known fix?

**Comment by seathasky** [comment]
Our website has a troubleshooting section just for this issue: https://www.xivmac.com/troubleshooting#q-black-textures?
