### ISSUE TITLE
Steam login error

### ISSUE THREAD

**Issue by boris-dziundziuk** [marzent/XIV-on-Mac#28]
The error says: "The login servers did not present the login challenge the way we were expecting. It may have changed on the server. Please check for an update to XIV on Mac to fix this. In the meantime please use the default launcher."

After it appears, launcher is starting with black screen and closes in a few seconds.
I'm using 3.0.0 XIV on Mac at Macbook Pro 16 with M1 Pro. Mac OS Monterey 12.2.1 (21D62)

**Comment by marzent** [comment]
For Steam login you need to use the latest version (or at least >=3.1) you can find the latest release as of today here https://github.com/marzent/XIV-on-Mac/releases/tag/v3.1.4

Also normally the app auto-updates itself, unless it has not been moved from the location it has been downloaded to

**Comment by zmactep** [comment]
Hi! I have the troubles with login (Steam account) on MacBook Pro 14 (M1 Max) with the 3.1.4 version of the launcher.
![4E2773D3-9286-4A79-B482-D5750546F87B](https://user-images.githubusercontent.com/1034785/158683363-56b4f006-0ecc-4a93-baa5-d08c54c3cbaa.jpeg)

Official launcher on Windows runs fine.

**Comment by seathasky** [comment]
Double check that you have Steam license checked in XIV on Mac launcher preferences and that you have properly linked your Square/Steam account in Windows. You will also need to have the Mac Steam application open in the background when logging in.

If you need any more information, we explain this in our setup guide here: https://www.xivmac.com/launcher-setup-guide

**Comment by zmactep** [comment]
```
You will also need to have the Mac Steam application open in the background when logging in.
```

Missed that. Now it runs, thank you!
