### ISSUE TITLE
ACT mod unresponsive on v3.1.4

### ISSUE THREAD

**Issue by mind8592** [marzent/XIV-on-Mac#29]
Hi all,

First of all, thank you for providing this wonderful tool.
It worked very well on my Intel Mac, which is reassuring because I'm looking at Mac upgrading options.

One of the main tools I use together with my Bootcamp version of FF14 is the Advanced Combat Tracker.
It appears the ACT parser does not work on the version of XIV on Mac I have installed - v3.1.4.

I was able to install ACT by following the guides on https://www.xivmac.com/act-parser. (It is a bit out dated for v3.1.4)
However I cannot launch the executable after installation.
I can launch the uninstall executable but not the one that starts the main ACT app.

**Comment by seathasky** [comment]
The ACT install video guide will be updated after we fix some things in beta.

In the current beta, you just need to make sure all of the .NET dependencies are installed. After you have installed all of .NET from the install menu, ACT should run using the "Start ACT" or "Auto-Launch ACT" in the ACT section

![Screen Shot 2022-03-18 at 4 20 52 PM](https://user-images.githubusercontent.com/17598024/159077884-2c61b9a8-677a-4d7b-845d-aa322137734d.png)

**Comment by seathasky** [comment]
https://www.xivmac.com/act-parser
I just updated the guide for beta. It's temporary but should fix your issue.

**Comment by mind8592** [comment]
Hey, thanks for the reply.
I’ve already installed all of the .NET dependencies.
Without installing .NET dependencies I’d be getting a warning during the installation of ACT.
Are there any log files I can look into to debug the issue?
