### ISSUE TITLE
Enabling Auto-OTP

### ISSUE THREAD

**Issue by rsahlstrom** [marzent/XIV-on-Mac#34]
After upgrading to 3.2.3, I tried enabling auto-otp today but it was always generating the wrong OTP. Looking at the keychain, nothing was being saved in the "\(username)(OTP secret)" secret. I saw OTP.swift had changes in 3.2.3 and so tried reverting to 3.1.4 and that worked and the keychain secret had the correct value in it.

I believe the issue is with these changes but don't know enough Swift to correctly supply a PR:

https://github.com/marzent/XIV-on-Mac/blob/cd9eb9e7ae91e4ef60033f3c03f6988a5568409e/XIV%20on%20Mac/Launcher/OTP.swift#L53-L55

**Comment by marzent** [comment]
Yeah all encryption has been rewritten to not need 5 different packages but rather rely on CommonCrypto only…
Will take a look at the issue, thanks for bringing it up

**Comment by marzent** [comment]
Fixed with 8ad2001330d0a8729bea236af54697329721dd28
