### ISSUE TITLE
Unable to create character config data

### ISSUE THREAD

**Issue by Roppest** [marzent/XIV-on-Mac#35]
Login is successful however when selecting character, the game can't start due to _Unable to create character config data_ error
as shown in image
![Screen Shot 2022-03-25 at 19 28 14](https://user-images.githubusercontent.com/26509815/160219381-100260f4-97b6-462c-ab38-dc121a1cb68f.png)

### Tried creating a new character but the error persists

System Specs:

- Model Name:	Mac mini
-   Model Identifier:	Macmini9,1
-   Chip:	Apple M1
-   Total Number of Cores:	8 (4 performance and 4 efficiency)
-   Memory:	16 GB
-   System Firmware Version:	7459.101.2
-   OS Loader Version:	7459.101.2

**Comment by Roppest** [comment]
Forgot to mention the OS version:  macOs Monterey v12.3

**Comment by FleetAdmiralButter** [comment]
Hello!

Could you please check that the application has access to your Documents folder:
![image](https://user-images.githubusercontent.com/37036084/160233579-e29c2208-ccdb-4fdb-b265-1fdcb7640876.png)

**Comment by Roppest** [comment]
Thank you for the quick response, I can confirm it does.

![image](https://user-images.githubusercontent.com/26509815/160243641-e34921e1-ed24-4f09-9598-ae1e5cd07452.png)

**Comment by seathasky** [comment]
Are you still having this issue @Roppest ?

**Comment by Roppest** [comment]
Yes I still have this issue
![image](https://user-images.githubusercontent.com/26509815/165587769-4b838911-421f-4380-8100-9dce1a397b11.png)

**Comment by seathasky** [comment]
Use our Discord support channel

**Comment by marzent** [comment]
Fixed with 4.0
