### ISSUE TITLE
Hitting enter in OTP field doesn't login

### ISSUE THREAD

**Issue by snowoutwith** [marzent/XIV-on-Mac#36]
Pressing the enter/return key after filling in the OTP no longer triggers the login process; I can tab to the username field and hit enter there and it works.

I *think* this started after upgrading to 3.3 but I'm not 100% sure of that; it certainly is happening in 3.3.1.

**Comment by marzent** [comment]
Hm I wonder if it ever worked correctly…
Anyhow should be fixed in the next release

**Comment by marzent** [comment]
No idea why this wasn't working but it definitely does as of now

**Comment by snowoutwith** [comment]
So this happened again and this time I was caffeinated enough to do a bit of debugging; the problem seems to be that when a text field's tooltip is present, the enter key isn't triggering a login attempt.

<img width="1077" alt="Screenshot 2022-04-02 at 13 38 39" src="https://user-images.githubusercontent.com/102404384/161384091-0613db04-209c-40d8-b81c-07aff8bfd148.png">

This is true of the password field as well. whenever there's a tooltip under one of the text entry fields hitting enter does nothing.

https://user-images.githubusercontent.com/102404384/161384496-d32bb883-2758-4047-949f-5f5ecf06dce4.mp4

I seem to be able to consistently trigger the tooltip by clearing the OTP field then tabbing into it then typing into the field.

Happy to continue debugging to help reproduce or to try out test fixes!

**Comment by marzent** [comment]
Hm this is due to cocoas incomplete OTP Content Type implementation I think; removing the flag also removes that popup which in turn allows to press enter

**Comment by marzent** [comment]
Ok now THAT specific issue is fixed with 3.4.4
Let me know if there are still issues!

**Comment by snowoutwith** [comment]
LGTM!
