### ISSUE TITLE
The login servers did not accept the request

### ISSUE THREAD

**Issue by boris-dziundziuk** [marzent/XIV-on-Mac#37]
The login servers did not accept the request. Please make sure you have a stable network connection to the FFXIV servers.
<img width="258" alt="Знімок екрана 2022-03-31 о 17 20 57" src="https://user-images.githubusercontent.com/11512414/161077777-e6a45ade-6094-493f-9872-288ea76a7523.png">
I'm using Steam version, Steam is running.

XIVonMac version 3.3.2 (33), MacOS 12.2.1, Macbook Pro 16 M1 Pro

**Comment by boris-dziundziuk** [comment]
I've previously played on Windows at Steam

**Comment by marzent** [comment]
You need to link on Windows after the account linking was introduced
