### ISSUE TITLE
No area of effect visuals from enemies 

### ISSUE THREAD

**Issue by MykolaGolubyev** [marzent/XIV-on-Mac#44]
Hello,
been away from the game, came back, got a few updates in, including DXVK
during boss fights I can't see usual red circles on the ground.
Also can't see placement of shields for scholar.

Cleared shader cache and restarted but no luck. 

Went through issues on GitHub but didn't see similar problem or solution

**Comment by Gabcddrc** [comment]
I also have the same issue.

**Comment by marzent** [comment]
This is a bug in the game that can be exasparated by DXVK shader compilation. A simple restart or shader cache reset should fix it.
