### ISSUE TITLE
Can't save state on settings

### ISSUE THREAD

**Issue by akihisa-higuchi** [marzent/XIV-on-Mac#50]
Hello, thanks for this useful software.

I updated to version 3.6. It can't save state on settings.

SettingsGeneralController.swift is work. But, SettingsGraphicsController.swift and SettingsPluginsController.swift and SettingsAdvancedController.swift are not working.

**Comment by cbackas42** [comment]
Thank you for the report, a few folks on Discord also brought this up and I found the problem on some items. I plan to have a fix available tonight.

**Comment by akihisa-higuchi** [comment]
Thank you !

**Comment by marzent** [comment]
Fixed with 680bd51a895b8e924b242f0e175123726f098188
