### ISSUE TITLE
3.6.2 Update Improperly Signed

### ISSUE THREAD

**Issue by mcmillion** [marzent/XIV-on-Mac#52]
Trying to install the 3.6.2 update from 3.5.7 and get the following:

```
Update Error!

The update is improperly signed and
could not be validated. Please try again
later or contact the app developer.
```

**Comment by seathasky** [comment]
Sounds like your app was corrupted or changed prior to opening it. If you are running software such as Bitdefender or other AV, would be advised to allow them to pass the app prior to open. Apple will verify all apps regardless.

**Comment by marzent** [comment]
3.6.2 is 100% properly signed as are the other updates, Sparkle wouldn't generate delta updates in its current configuration otherwise
