### ISSUE TITLE
Terminate ACT after XIV executable shuts down

### ISSUE THREAD

**Issue by Cellane** [marzent/XIV-on-Mac#54]
I hope this is not just some misconfiguration on my side but while XOM is happy to auto-launch ACT and/or BunnyHUD on game start, it doesn’t terminate either of those two when the game shuts down.

When you launch the game next time, XOM will try to open (likely) both ACT and BunnyHUD again. BunnyHUD, being a native app, won’t be open again, but ACT will happily launch multiple times, and then behave like bad siblings to each other and start fighting between various running instances of ACT.

I think it would be lovely if XOM could not just auto-start but also auto-close ACT and BunnyHUD when the game binary is detected as not running anymore. If that’s not possible, I think not launching another instance of ACT on game start if the previous instance is detected as still running would be a nice workaround.

One more thing, though that might be a separate ticket, please let me know if I should separate it (or if it’s even wanted in the first place), I think I saw someone mention that ACT is more stable when launched after logging into the game. That might of course be troublesome to detect, but adding a configurable delay between launching XIV and launching ACT might serve as a workaround as well?

Thank you for considering adding (either of) those! And thanks for your amazing work thus far.

**Comment by marzent** [comment]
From my personal experience ACT stability is unaffected by login delay, but if it actually does help it is an option that could be added. 

Regarding ACT closing with the game, it is easiest to just close the game by quitting XOM itself which will get rid of all running wine processes started by XOM. 

Having said that it would not be impossible to implement above behavior, however ACT support is in a rough state overall at the moment; will need to think about how to handle that best in the future.

**Comment by Cellane** [comment]
I see! I never tried closing XOM completely I suppose – I keep it running so that I can start the game at any point by just pressing the Enter key for extra convenience. But you’re right, since XOM is a native app and starts so quickly, there’s also no reason not to keep it open. (Though technically just to be super nitpicky, quitting XOM for sure terminates ACT but keeps BunnyHUD running, it would be nice if both could be terminated, I think. Small things though!)

Thank you for getting back to me
