### ISSUE TITLE
Flickering lights

### ISSUE THREAD

**Issue by Ceolona** [marzent/XIV-on-Mac#6]
Not necessarily specific to XIV on Mac...

The Ocular (Crystarium) show significant flicker/throbbing under certain conditions.  It appears to be connected to Occlusion Culling, Glare and camera angle.

Setting Glare to "Off" and turning off Occlusion Culling minimizes the flicker, if not stops it.  Combinations of both/either have flicker in varying degrees.

**Comment by marzent** [comment]
Even though I marked this as bug this issue is almost certainly a MoltenVK limitation…

I should really collect some more info on it and file another issue there

**Comment by marzent** [comment]
For reference the current MVK issue https://github.com/KhronosGroup/MoltenVK/issues/1542

**Comment by marzent** [comment]
Fixed with eda35bc59d6c42140c0b6b19d307b1e3b359b338
