### ISSUE TITLE
Login system error 

### ISSUE THREAD

**Issue by JulioGuercioni** [marzent/XIV-on-Mac#61]
The login servers did not accept the request. Please make sure you have a stable network connection to the FFXIV servers.

Step 1. I updated the app when it launched.
Step 2. I selected my FF14 version (steam free trial). 
Step 3. I launched the steam application on mac and login. 
Step 4. I let the launcher download the game.
Step 5. Login again and i get the following error

Any help is appreciated thank you :).

<img width="1230" alt="Screen Shot 2022-05-21 at 11 04 02 PM" src="https://user-images.githubusercontent.com/21230810/169676685-d7662af8-3ddf-4b76-9759-f7f6dc2d6df7.png">

**Comment by marzent** [comment]
You need to link team accounts on a Windows machine once, same as https://github.com/marzent/XIV-on-Mac/issues/37

**Comment by JulioGuercioni** [comment]
Correct me if I'm wrong but i think my account is link :/. 

1) When i launch the game on windows (steam) my Square Enix Id is not editable.
2) On the Mog Station i have free trial (steam) for the version use on my account.

I'm pretty sure that means that i link my account but i could be wrong. Thank you again for the help :)

![Launcher](https://user-images.githubusercontent.com/21230810/169706059-d0ac5009-a979-4e82-958c-6014d5c66de4.JPG)
![Mog Station FF14](https://user-images.githubusercontent.com/21230810/169706060-a47b7ea8-d0d7-41b7-9477-18459254adfe.JPG)
