### ISSUE TITLE
Game crashes in Azys Lla

### ISSUE THREAD

**Issue by phompraseut** [marzent/XIV-on-Mac#68]
[backtrace.txt](https://github.com/marzent/XIV-on-Mac/files/8800889/backtrace.txt)

For some reason whenever I enter this zone, the game will crash and I'll get the attached error message. This usually happens when I'm in the zone for a long period of time or if I'm watching cutscenes. FWIW I don't seem to have these issues in other zones. and I've been everywhere up to end walker.

**Comment by seathasky** [comment]
Known issue. Turn on Modern MoltenVK in XIV on Mac's Launcher preferences. 
![Screen Shot 2022-05-30 at 9 12 25 PM](https://user-images.githubusercontent.com/17598024/171073966-15d73f48-1164-4e16-b423-3ef13105adf7.png)
