### ISSUE TITLE
Error "Could Not Get STORED"

### ISSUE THREAD

**Issue by alexjacket** [marzent/XIV-on-Mac#73]
Impossible to log in into the game using a steam license. Appears the error "could not get stored"
![Captura de Tela 2022-06-23 às 15 23 01](https://user-images.githubusercontent.com/61524572/175368500-586b6db5-dce4-4372-9a9b-51c7828f0128.png)

current stable steam version (as of 23 of June, 2022)
no mods other than dalamud
macOS 12.4 
Mac Mini M1, 8gb

**Comment by marzent** [comment]
This is an issue on SEs side since their login servers do not respond to steam requests if steam is down (steam summer sale).
The official launcher also does not work
