### ISSUE TITLE
Internal Dalamud Error Has Occurred

### ISSUE THREAD

**Issue by Aquaeyes** [marzent/XIV-on-Mac#86]
I was unable to use gshade, so, I selected in the XIVonMac toolbar to attempt to install gshade manually, and selected to update it in there, however, now I'm getting 'Internal Dalamud Error has Occurred' when attempting to start the game, despite Dalamud being disabled in the XIVonMAC settings.
[launcher.log](https://github.com/marzent/XIV-on-Mac/files/9630367/launcher.log)

Is there a way to reinstall just this section without needing to reinstall FFXIV itself again?

**Comment by FleetAdmiralButter** [comment]
Hi,

The latest version of Gshade now requires AVX, which isn’t available under Rosetta.

Please follow these instructions in our Discord to install the legacy GShade DLLs: https://discord.com/channels/915959680080171018/980488014096654397/1021957799858667520

**Comment by Michcioperz** [comment]
If I understand correctly, the instructions essentially boil down to going to `~/.local/share/GShade` directory and copying the dlls out of the `Legacy (Non-AVX)` into the GShade directory, is that right?

**Comment by marzent** [comment]
Closing this since this could only happen with GShade AVX dlls and not really a XOM issue
