### ISSUE TITLE
Wine crash on game exit when Dalamud enabled

### ISSUE THREAD

**Issue by chipgeekjr** [marzent/XIV-on-Mac#88]
As the title says, i get a wine crash window when closing the game with dalamud enabled, with or without any plugins installed.

Logs from the past few times:
[backtrace-9-11-22.txt](https://github.com/marzent/XIV-on-Mac/files/9638092/backtrace-9-11-22.txt)
[backtrace-9-17-22.txt](https://github.com/marzent/XIV-on-Mac/files/9638093/backtrace-9-17-22.txt)
[backtrace-9-18-22.txt](https://github.com/marzent/XIV-on-Mac/files/9638094/backtrace-9-18-22.txt)
[backtrace-9-24-22.txt](https://github.com/marzent/XIV-on-Mac/files/9638095/backtrace-9-24-22.txt)

**Comment by PascalTemel** [comment]
Same for me

**Comment by Ultima2876** [comment]
I also have the same problem.

[crashbacktrace.txt](https://github.com/marzent/XIV-on-Mac/files/9742909/crashbacktrace.txt)

**Comment by JordanDWhalen** [comment]
Same here!

**Comment by marzent** [comment]
Duplicate of https://github.com/marzent/XIV-on-Mac/issues/84
